"""empty message

Revision ID: 0b96d5d9dbdb
Revises: 76d395bf1323
Create Date: 2022-11-25 10:17:49.690072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b96d5d9dbdb'
down_revision = '76d395bf1323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'description')
    # ### end Alembic commands ###
