"""empty message

Revision ID: f35f0953479a
Revises: 775d350eaa0d
Create Date: 2022-11-29 13:48:38.309418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35f0953479a'
down_revision = '775d350eaa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planet_name', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'favorites', 'planets', ['planet_name'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'planet_name')
    # ### end Alembic commands ###
