"""empty message

Revision ID: fe79ec6d3fae
Revises: 0b96d5d9dbdb
Create Date: 2022-11-25 10:56:58.946316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe79ec6d3fae'
down_revision = '0b96d5d9dbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
